#!/bin/sh
tarsnap -c -f "mybackup-$(date +%Y%m%d%H%M%S)" --cachedir /home/flo/.tarsnap-cache --keyfile /root/tarsnap.key -X /home/flo/tarsnap-excludes.txt --print-stats  --checkpoint-bytes 300000000 /home/flo/
